name: 'Docker Extract'
description: 'Extract file(s) from a Docker Image'
author: 'Samuel Ryan <sam@samryan.co.uk>'
inputs:
  image:
    description: 'Docker Image to extract files from'
    required: true
  path:
    description: 'Path (from root) to a file or directory within Image'
    required: true
  platform:
    description: 'The platform the image was built for'
    required: true
    default: 'linux/amd64'
outputs:
  destination:
    description: 'Destination of extracted file(s)'
  platform:
    description: 'The platform the image was built for'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'scissors'
  color: 'blue'
